//
//  MapScreenInteractor.swift
//  MapPlaces
//
//  Created TOOK on 27.12.2019.
//  Copyright © 2019 TOOK. All rights reserved.
//
//  Template generated by Sakhabaev Egor @Banck
//  https://github.com/Banck/Swift-viper-template-for-xcode
//

import UIKit

class MapScreenInteractor: MapScreenInteractorInput {
    // MARK: - Properties
    weak var presenter: MapScreenInteractorOutput?
    
    // MARK: - MapScreenInteractorInput -

}
