//
//  MapScreenRouter.swift
//  MapPlaces
//
//  Created TOOK on 27.12.2019.
//  Copyright © 2019 TOOK. All rights reserved.
//
//  Template generated by Sakhabaev Egor @Banck
//  https://github.com/Banck/Swift-viper-template-for-xcode
//

import UIKit

class MapScreenRouter {
    // MARK: - Properties
    weak var viewController: UIViewController?
}

// MARK: - MapScreenWireframeInterface -
extension MapScreenRouter: MapScreenWireframeInterface {
    
    func navigate(to option: MapScreenNavigationOption) {
//        switch option {
//        case .firstModule:
//              openFirstModule()
//        case .secondModule(let someData):
        //      openSecondModule(with someData)
//        }
    }
}
