//
//  MapScreenConfigurator.swift
//  MapPlaces
//
//  Created TOOK on 27.12.2019.
//  Copyright © 2019 TOOK. All rights reserved.
//
//  Template generated by Sakhabaev Egor @Banck
//  https://github.com/Banck/Swift-viper-template-for-xcode
//

import UIKit

struct MapScreenConfigurator {

	static func createModule() -> UIViewController {
        var view: MapScreenViewController!

        let viewController = UIStoryboard.init(name: "MapScreen", bundle: Bundle.main).instantiateInitialViewController()
        if viewController == nil {
            fatalError("Seems there is no initial view controller in MapScreen.storyboard")
        }

        if viewController is UINavigationController {
            view = (viewController as? UINavigationController)?.viewControllers.first as? MapScreenViewController
        } else {
            view = viewController as? MapScreenViewController
        }

        let interactor = MapScreenInteractor()
        let router = MapScreenRouter()
        let presenter = MapScreenPresenter(interface: view, interactor: interactor, router: router)
        
        view.presenter = presenter
        interactor.presenter = presenter
        router.viewController = view
        
        return viewController!
    }
}
