//
//  PhotosInteractor.swift
//  MapPlaces
//
//  Created TOOK on 19.01.2020.
//  Copyright © 2020 TOOK. All rights reserved.
//
//  Template generated by Sakhabaev Egor @Banck
//  https://github.com/Banck/Swift-viper-template-for-xcode
//

import UIKit

class PhotosInteractor: PhotosInteractorInput {
    // MARK: - Properties
    weak var presenter: PhotosInteractorOutput?
    
    // MARK: - PhotosInteractorInput -

}
