//
//  PhotosConfigurator.swift
//  MapPlaces
//
//  Created TOOK on 19.01.2020.
//  Copyright © 2020 TOOK. All rights reserved.
//
//  Template generated by Sakhabaev Egor @Banck
//  https://github.com/Banck/Swift-viper-template-for-xcode
//

import UIKit

struct PhotosConfigurator {

	static func createModule() -> UIViewController {
        var view: PhotosViewController!

        let viewController = UIStoryboard.init(name: "Photos", bundle: Bundle.main).instantiateInitialViewController()
        if viewController == nil {
            fatalError("Seems there is no initial view controller in Photos.storyboard")
        }

        if viewController is UINavigationController {
            view = (viewController as? UINavigationController)?.viewControllers.first as? PhotosViewController
        } else {
            view = viewController as? PhotosViewController
        }

        let interactor = PhotosInteractor()
        let router = PhotosRouter()
        let presenter = PhotosPresenter(interface: view, interactor: interactor, router: router)
        
        view.presenter = presenter
        interactor.presenter = presenter
        router.viewController = view
        
        return viewController!
    }
}
