//
//  PhotosPresenter.swift
//  MapPlaces
//
//  Created TOOK on 19.01.2020.
//  Copyright © 2020 TOOK. All rights reserved.
//
//  Template generated by Sakhabaev Egor @Banck
//  https://github.com/Banck/Swift-viper-template-for-xcode
//

import UIKit

class PhotosPresenter {
    // MARK: - Properties
    weak private var view: PhotosView?
    var interactor: PhotosInteractorInput?
    private let router: PhotosWireframeInterface

    // MARK: - Initialization and deinitialization -
    init(interface: PhotosView, interactor: PhotosInteractorInput?, router: PhotosWireframeInterface) {
        self.view = interface
        self.interactor = interactor
        self.router = router
    }

}

// MARK: - PhotosPresenterInterface -
extension PhotosPresenter: PhotosPresenterInterface {
    
}

// MARK: - PhotosInteractorOutput -
extension PhotosPresenter: PhotosInteractorOutput {
    
}

