//
//  PhotosRouter.swift
//  MapPlaces
//
//  Created TOOK on 19.01.2020.
//  Copyright © 2020 TOOK. All rights reserved.
//
//  Template generated by Sakhabaev Egor @Banck
//  https://github.com/Banck/Swift-viper-template-for-xcode
//

import UIKit

class PhotosRouter {
    // MARK: - Properties
    weak var viewController: UIViewController?
}

// MARK: - PhotosWireframeInterface -
extension PhotosRouter: PhotosWireframeInterface {
    
    func navigate(to option: PhotosNavigationOption) {
//        switch option {
//        case .firstModule:
//              openFirstModule()
//        case .secondModule(let someData):
        //      openSecondModule(with someData)
//        }
    }
}
